### ISSUE TITLE
Great meeting you all! Left you a gift

### ISSUE THREAD

**Issue by daviddias** [gdglisbon/gdglisbon.github.io#5]
It was a pleasure meeting the GDGTeam today after all these years :) Amazed with the stellar work you are doing 🌟

Here is the logo you were looking for:
![image](https://user-images.githubusercontent.com/1211152/32693810-c414b46c-c728-11e7-869b-4ea051cca8e2.png)
https://github.com/gdglisbon/group/blob/master/BIG%20Slash.png
(unfortunately only managed to find a high res .png and not the .svg)

Let me know if I can help in any capacity :)

**Comment by OldMetalmind** [comment]
@daviddias obrigado!
